services:
  redishost:
    container_name: pypeline_redis
    image: redis:alpine
    ports:
      - 6379:6379
  pypeline:
    container_name: pypeline
    hostname: pypeline
    volumes:
      - ./test:/work/test
    build:
      context: .
    depends_on:
      - redishost
    environment:
      - PYTHONPATH=/work/test/
    command: pypeline 0 test -vvv --redis-hostname redishost --redis-port 6379 -kv "#STAGES=printout" "PRINTOUT_INP=test" "PRINTOUT_ARG=--sleep 5" "#CONTEXTENV=ENVKEY=ENVVALUE1:ENVVALUE2"
  watcher_pypeline:
    container_name: watcher_pypeline
    hostname: watcher_pypeline
    volumes:
      - ./test:/work/test
    build:
      context: .
    depends_on:
      - redishost
    environment:
      - PYTHONPATH=/work/test/
    command: pypeline 0 watcher -vvv --redis-hostname redishost --redis-port 6379 -kv "#STAGES=printout" "PRINTOUT_INP=watcher" "PRINTOUT_ARG=--sleep 0" "#CONTEXTENV=TARGET_HOSTNAME=pypeline TARGET_ENUMERATION=0 REDIS_HOSTNAME=redishost REDIS_PORT=6379"